// RemBeetle frontend: backend origin configuration.
//
// null  -> the backend is the same origin that served this page (EC2 behind Caddy,
//          or http://localhost:12393 during development). This is the historical behaviour.
// "https://api.rembeetle.com" -> the frontend is hosted separately (e.g. on Vercel) and all
//          WebSocket/HTTP traffic goes to that backend origin instead.
//
// Do not edit this file for Vercel: vercel-build.sh generates dist/config.js from the
// REMAI_BACKEND_ORIGIN environment variable of the Vercel project.
window.REMAI_BACKEND_ORIGIN = null;
