#!/usr/bin/env bash
# Build the RemBeetle static frontend for Vercel into ./dist
#
# Vercel project settings:
#   Framework Preset : Other
#   Root Directory   : frontend
#   Environment var  : REMAI_BACKEND_ORIGIN = https://api.rembeetle.com   (Production + Preview)
#
# The backend (FastAPI + WebSockets) is NOT deployed to Vercel; it keeps running on EC2 and
# this frontend talks to it at REMAI_BACKEND_ORIGIN. The same files, served by the backend
# itself with config.js = null, keep working exactly as before.
set -euo pipefail
cd "$(dirname "$0")"

: "${REMAI_BACKEND_ORIGIN:?Set REMAI_BACKEND_ORIGIN (e.g. https://api.rembeetle.com) as an Environment Variable of the Vercel project}"
ORIGIN="${REMAI_BACKEND_ORIGIN%/}"

case "$ORIGIN" in
  https://*) ;;
  http://*)  echo "WARNING: $ORIGIN is http://; browsers will block it as mixed content on an https page." ;;
  *)         echo "ERROR: REMAI_BACKEND_ORIGIN must look like https://host[:port] (got '$ORIGIN')"; exit 1 ;;
esac

# The Content-Security-Policy in vercel.json must allow the backend host, otherwise the browser
# silently blocks images, the Live2D model and the WebSocket. Every host token in the CSP is
# followed by a space or a ';', so a fixed-string check is enough.
HOST="${ORIGIN#*://}"
if ! grep -qF -- "://$HOST " vercel.json && ! grep -qF -- "://$HOST;" vercel.json; then
  echo "ERROR: the Content-Security-Policy in vercel.json does not allow '$HOST'."
  echo "       Update img-src, connect-src and media-src in vercel.json to include https://$HOST"
  exit 1
fi

rm -rf dist
mkdir -p dist/assets dist/libs dist/web-tool
cp index.html auth-shell.js favicon.ico rem.ico rem.jpg dist/
cp assets/* dist/assets/
cp libs/*   dist/libs/

# Generated per-environment config (overrides the null default checked into git).
printf '// generated by vercel-build.sh\nwindow.REMAI_BACKEND_ORIGIN = "%s";\n' "$ORIGIN" > dist/config.js

# /web-tool lives on the backend; keep the old URL working from the Vercel domain.
{
  echo '<!doctype html><meta charset="utf-8"><title>RemAI web tool</title>'
  echo "<meta http-equiv=\"refresh\" content=\"0; url=${ORIGIN}/web-tool/\">"
  echo "<a href=\"${ORIGIN}/web-tool/\">Continue to the web tool</a>"
} > dist/web-tool/index.html

echo "Built dist/ for backend origin $ORIGIN"
echo "dist size: $(du -sh dist | cut -f1), files: $(find dist -type f | wc -l)"
